version: 2.1
description: |
  Anchore Engine is a docker container static analysis and policy-based compliance tool that
  automates the inspection, analysis, and evaluation of images to allow high confidence in
  container deployments by ensuring workload content meets the required criteria.
  Anchore Engine Project - https://github.com/anchore/anchore-engine
  Orb source code - https://github.com/anchore/ci-tools/blob/master/circleci-orbs/anchore-engine/orb.yml

examples:
  standard_image_scan:
    description: |
      Use this job to scan an image located in a public registry. A custom
      policy can be used for evaluation, add custom Anchore policy bundle to
      .circleci/.anchore/policy_bundle.json in your repo.
    usage:
      version: 2.1
      orbs:
        anchore: anchore/anchore-engine@1.2.0
      workflows:
        scan_image:
          jobs:
            - anchore/image_scan:
                image_name: docker.io/anchore/anchore-engine:latest
                timeout: '300'

  private_image_scan:
    description: |
      Use this job to scan an image located in a private registry. A custom
      policy can be used for evaluation, add custom Anchore policy bundle to
      .circleci/.anchore/policy_bundle.json in your repo.
    usage:
      version: 2.1
      orbs:
        anchore: anchore/anchore-engine@1.2.0
      workflows:
        scan_image:
          jobs:
            - anchore/image_scan:
                image_name: docker.io/anchore/anchore-engine:latest
                private_registry: True
                registry_name: docker.io
                registry_user: "${DOCKER_USER}"
                registry_pass: "${DOCKER_PASS}"

  local_image_scan:
    description: |
      Use the analyze_local_image command within a container build pipeline,
      it can be used to scan an image that hasn'tbeen pushed to a registry yet.
      If Anchore policy evaluation gives 'fail' status, the CI job will be marked
      as a failure. A custom policy can be used for evaluation, add custom Anchore
      policy bundle to .circleci/.anchore/policy_bundle.json in your repo.
    usage:
      version: 2.1
      orbs:
        anchore: anchore/anchore-engine@1.2.0
      jobs:
        local_image_scan:
          executor: anchore/anchore_engine
          steps:
            - checkout:
                path: ~/project/src/
            - run:
                name: build container
                command: docker build -t "${CIRCLE_PROJECT_REPONAME}:ci" ~/project/src/
            - anchore/analyze_local_image:
                image_name: ${CIRCLE_PROJECT_REPONAME}:ci
                timeout: '500'
                policy_failure: True
            - anchore/parse_reports

executors:
  anchore_engine:
    description: Machine runner with anchore engine default environment variables set.
    parameters:
      anchore_engine_version:
        description: Version of anchore-engine container to run (recommended to keep default value)
        type: string
        default: "v0.3.2"
    environment:
      ANCHORE_CLI_USER: admin
      ANCHORE_CLI_PASS: foobar
      ANCHORE_CLI_SSL_VERIFY: 'n'
      ANCHORE_VERSION: << parameters.anchore_engine_version >>
    machine:
      image: circleci/classic:201808-01

commands:
  add_private_registry:
    description: |
      Adds credentials for private registries to anchore engine.
      Set registry credentials with $DOCKER_USER & $DOCKER_PASS env vars.
      Must run on executor with anchore-engine running & anchore-cli installed.
    parameters:
      registry_name:
        description: Name of private registry (eg - docker.io).
        type: string
        default: "docker.io"
      registry_user:
        description: Username for private registry (use env var to populate).
        type: string
        default: "${DOCKER_USER}"
      registry_pass:
        description: Password for private registry (use env var to populate).
        type: string
        default: "${DOCKER_PASS}"
    steps:
      - run:
          name: Add private registry credentials to anchore engine.
          command: anchore-cli registry add << parameters.registry_name >> << parameters.registry_user >> << parameters.registry_pass >> --skip-validate

  analyze_local_image:
    description: |
      Pushes a local image to a temporary registry container.
      Image is then scanned with anchore engine. Stores all reports as artifacts.
      Must be run on executor with docker-compose & sudo.
    parameters:
      policy_bundle_file_path:
        description: Specify file path to policy bundle.
        type: string
        default: "/home/circleci/project/.circleci/.anchore/policy_bundle.json"
      policy_failure:
        description: Set to True if pipeline should stop on policy evaluation status 'fail'.
        type: boolean
        default: False
      image_name:
        description: Image repository & tag (eg - "docker.io/anchore/anchore-engine:latest").
        type: string
      timeout:
        description: Timeout used for Anchore Engine image scanning.
        type: string
        default: "300"
    steps:
      - install_tools
      - setup_anchore_engine
      - run:
          name: Start registry container & push local image.
          command: |
            cat \<< EOF \>> docker-compose.yaml

              anchore-registry:
                image: "registry:latest"
                ports:
                - "5000:5000"
            EOF
            docker-compose up -d
            echo "127.0.0.1 anchore-registry" | sudo tee -a /etc/hosts > /dev/null
            echo "Waiting for registry to start..."
            sleep 15
            docker tag << parameters.image_name >> anchore-registry:5000/<< parameters.image_name >>
            docker push anchore-registry:5000/<< parameters.image_name >>
      - analyze_image:
          image_name: anchore-registry:5000/<< parameters.image_name >>
          timeout: << parameters.timeout >>
      - policy_evaluation:
          image_name: anchore-registry:5000/<< parameters.image_name >>
          policy_failure: << parameters.policy_failure >>
          policy_bundle_file_path: << parameters.policy_bundle_file_path >>
      - parse_reports
      - store_artifacts:
          path: anchore-reports

  analyze_image:
    description: |
      Add image to anchore engine and start analyzing.
      image_name is required, timeout is optional.
      Must run on executor with anchore_ci_tools.py & anchorecli installed.
    parameters:
      image_name:
        description: Image repository & tag (eg - "docker.io/anchore/anchore-engine:latest").
        type: string
      timeout:
        description: Timeout used for Anchore Engine image scanning.
        type: string
        default: "300"
    steps:
      - run:
          name: Analyze image with anchore engine.
          command: |
            anchore_ci_tools --analyze --report --image << parameters.image_name >> --timeout << parameters.timeout >>
            anchore-cli image get << parameters.image_name >>
  
  install_tools:
    description: Install anchore_ci_tools.py
    steps:
      - run:
          name: Install anchore tools
          command: |
            # TODO Update script to pull from version tag
            curl -o /tmp/anchore_ci_tools.py https://raw.githubusercontent.com/anchore/ci-tools/orb_version_update/scripts/anchore_ci_tools.py
            chmod +x /tmp/anchore_ci_tools.py
            if [ -d "/home/circleci" ]; then
              pyenv global 3.6.5
              pip install --upgrade pip
              pip install --upgrade anchorecli
              sed -i 's|/usr/bin/python3|/opt/circleci/.pyenv/shims/python3|' /tmp/anchore_ci_tools.py
              ln -s /tmp/anchore_ci_tools.py /home/circleci/bin/anchore_ci_tools
            else
              ln -s /tmp/anchore_ci_tools.py /usr/local/bin/anchore_ci_tools
            fi

  parse_reports:
    description: Prints analysis report of package vulnerabilites using JQ.
    steps:
      - run:
          name: View parsed vulnerability analysis report.
          command: |
            printf "\n%s\n" "The following OS packages are installed:"
            jq '[.content | sort_by(.package) | .[] | {package: .package, version: .version}]' anchore-reports/image-content-os-report.json || true
            printf "\n%s\n" "The following vulnerabilites were found:"
            jq '[.vulnerabilities | group_by(.package) | .[] | {package: .[0].package, vuln: [.[].vuln]}]' anchore-reports/image-vuln-report.json || true
 
  policy_evaluation:
    description: |
      Perform policy evaluation using Anchore Engine image analysis. A customized policy bundle can be utilized for evaluation.
      Custom policy bundles should be added to your repo at .circleci/.anchore/policy_bundle.json. If using multiple policy
      bundles, or if using executor other than anchore/anchore_engine a custom policy bundle path can be set as a parameter.
    parameters:
      image_name:
        description: Image repository & tag (eg - "docker.io/anchore/anchore-engine:latest").
        type: string
      policy_failure:
        description: Set to True if pipeline should stop on policy evaluation status 'fail'.
        type: boolean
        default: False
      policy_bundle_file_path:
        description: Specify file path to policy bundle.
        type: string
        default: "~/project/src/.circleci/.anchore/policy_bundle.json"
    steps:
      - run:
          name: Evaluate image against desired policy bundle.
          command: |
            (anchore-cli --json policy add << parameters.policy_bundle_file_path >> | jq '.policyId' | xargs anchore-cli policy activate) &> /dev/null || \
              printf "\n%s\n" "Custom policy bundle not found - << parameters.policy_bundle_file_path >> - using default policy bundle."
            if << parameters.policy_failure >>; then
              anchore-cli evaluate check << parameters.image_name >> --detail
            else
              (set +o pipefail; anchore-cli evaluate check << parameters.image_name >> --detail | tee /dev/null)
            fi

  setup_anchore_engine:
    description: |
      Setup anchore-engine using docker compose and default configuration.
      Must be run on executor with anchore_ci_tools.py, anchorecli & docker-compose installed.
    parameters:
      anchore_engine_version:
        description: Version of anchore engine container.
        type: string
        default: "v0.3.2"
    steps:
      - run:
          name: Create anchore engine configuration files.
          command: |
            cat \<< EOF > docker-compose.yaml
            # Anchore engine docker-compose configuration.
            version: '2'
            volumes:
              anchore-scratch: {}
              anchore-db-volume: {}
            services:
              # The primary API endpoint service
              engine-api:
                image: anchore/anchore-engine:<< parameters.anchore_engine_version >>
                depends_on:
                - anchore-db
                - engine-catalog
                ports:
                - "8228:8228"
                logging:
                  driver: "json-file"
                  options:
                    max-size: 100m
                environment:
                - ANCHORE_ENDPOINT_HOSTNAME=engine-api
                - ANCHORE_DB_HOST=anchore-db
                - ANCHORE_DB_PASSWORD=mysecretpassword
                command: ["anchore-manager", "service", "start", "apiext"]

              # Catalog is the primary persistence and state manager of the system
              engine-catalog:
                image: anchore/anchore-engine:<< parameters.anchore_engine_version >>
                depends_on:
                - anchore-db
                logging:
                  driver: "json-file"
                  options:
                    max-size: 100m
                expose:
                - 8228
                environment:
                - ANCHORE_ENDPOINT_HOSTNAME=engine-catalog
                - ANCHORE_DB_HOST=anchore-db
                - ANCHORE_DB_PASSWORD=mysecretpassword
                command: ["anchore-manager", "service", "start", "catalog"]
              engine-simpleq:
                image: anchore/anchore-engine:<< parameters.anchore_engine_version >>
                depends_on:
                - anchore-db
                - engine-catalog
                expose:
                - 8228
                logging:
                  driver: "json-file"
                  options:
                    max-size: 100m
                environment:
                - ANCHORE_ENDPOINT_HOSTNAME=engine-simpleq
                - ANCHORE_DB_HOST=anchore-db
                - ANCHORE_DB_PASSWORD=mysecretpassword
                command: ["anchore-manager", "service", "start", "simplequeue"]
              engine-policy-engine:
                image: anchore/anchore-engine:<< parameters.anchore_engine_version >>
                depends_on:
                - anchore-db
                - engine-catalog
                expose:
                - 8228
                logging:
                  driver: "json-file"
                  options:
                    max-size: 100m
                environment:
                - ANCHORE_ENDPOINT_HOSTNAME=engine-policy-engine
                - ANCHORE_DB_HOST=anchore-db
                - ANCHORE_DB_PASSWORD=mysecretpassword
                command: ["anchore-manager", "service", "start", "policy_engine"]
              engine-analyzer:
                image: anchore/anchore-engine:<< parameters.anchore_engine_version >>
                depends_on:
                - anchore-db
                - engine-catalog
                expose:
                - 8228
                logging:
                  driver: "json-file"
                  options:
                    max-size: 100m
                environment:
                - ANCHORE_ENDPOINT_HOSTNAME=engine-analyzer
                - ANCHORE_DB_HOST=anchore-db
                - ANCHORE_DB_PASSWORD=mysecretpassword
                volumes:
                - anchore-scratch:/analysis_scratch
                command: ["anchore-manager", "service", "start", "analyzer"]
              anchore-db:
                image: anchore/engine-db-preload:<< parameters.anchore_engine_version >>
                volumes:
                - anchore-db-volume:/var/lib/postgresql/data
                environment:
                - POSTGRES_PASSWORD=mysecretpassword
                expose:
                - 5432
                logging:
                  driver: "json-file"
                  options:
                    max-size: 100m
            EOF

      - run:
          name: Start anchore engine.
          command: |
            pip install --upgrade docker-compose
            docker-compose up -d
            anchore-cli system wait --interval 10

jobs:
  image_scan:
    executor: anchore_engine
    description: |
      Performs a static security analysis of docker container with anchore engine.
      A custom policy can be used for evaluation, add custom Anchore policy bundle
      to .circleci/.anchore/policy_bundle.json in your repo. Anchore engine pulls
      image from public/private docker registries. Requires registry credentials
      to access private images, use ENV vars $DOCKER_USER & $DOCKER_PASS
    parameters:
      after_checkout:
        description: Optional steps to run after checking out the code.
        type: steps
        default: []
      before_analyze:
        description: Optional steps to run before analyzing the docker image.
        type: steps
        default: []
      after_analyze:
        description: Optional steps to run after analyzing the docker image.
        type: steps
        default: []
      image_name:
        description: Image repository & tag (eg - "docker.io/anchore/anchore-engine:latest").
        type: string
      policy_bundle_file_path:
        description: Specify file path to policy bundle.
        type: string
        default: "/home/circleci/project/.circleci/.anchore/policy_bundle.json"
      policy_failure:
        description: Set to True if pipeline should stop on policy evaluation status 'fail'.
        type: boolean
        default: False
      private_registry:
        description: Set to True if image is only accessible from a private registry.
        type: boolean
        default: False
      registry_name:
        description: Name of private registry (eg - "docker.io")
        type: string
        default: "docker.io"
      registry_user:
        description: Username for private registry (use env var $DOCKER_USER to populate).
        type: string
        default: "${DOCKER_USER}"
      registry_pass:
        description: Password for private registry (use env var $DOCKER_PASS to populate).
        type: string
        default: "${DOCKER_PASS}"
      timeout:
        description: Timeout used for Anchore Engine image scanning.
        type: string
        default: "300"
    steps:
      - checkout:
          path: ~/project/src/
      - when:
          name: Run after_checkout lifecycle hook steps.
          condition: << parameters.after_checkout >>
          steps: << parameters.after_checkout >>
      - install_tools
      - setup_anchore_engine
      - when:
          name: Run before_analyze lifecycle hook steps.
          condition: << parameters.before_analyze >>
          steps: << parameters.before_analyze >>
      - when:
          condition: << parameters.private_registry >>
          steps:
            - add_private_registry:
                registry_name: << parameters.registry_name >>
                registry_user: << parameters.registry_user >>
                registry_pass: << parameters.registry_pass >>
      - analyze_image:
          image_name: << parameters.image_name >>
          timeout: << parameters.timeout >>
      - when:
          name: Run after_analyze lifecycle hook steps.
          condition: << parameters.after_analyze >>
          steps: << parameters.after_analyze >>
      - policy_evaluation:
          image_name: << parameters.image_name >>
          policy_failure: << parameters.policy_failure >>
          policy_bundle_file_path: << parameters.policy_bundle_file_path >>
      - parse_reports
      - store_artifacts:
          path: anchore-reports
